apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iostokenvariants.push.aerogear.org
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.production
      name: Production
      type: boolean
    - JSONPath: .status.variantId
      name: VariantId
      type: string
    - JSONPath: .status.ready
      name: Ready
      type: string
  group: push.aerogear.org
  names:
    kind: IOSTokenVariant
    listKind: IOSTokenVariantList
    plural: iostokenvariants
    singular: iostokenvariant
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bundleId:
              description: BundleId is used if you are using APNs tokens as opposed
                to certificates.  Get this value from your APNS console.
              type: string
            description:
              description: Description is a human friendly description for the variant.
              type: string
            keyId:
              description: KeyId is used if you are using APNs tokens as opposed to
                certificates.  Get this value from your APNS console.
              type: string
            privateKey:
              description: PrivateKey is used if you are using APNs tokens as opposed
                to certificates.  Get this value from your APNS console, and ensure
                it is in p8 format
              type: string
            production:
              description: Production defines if a connection to production APNS server
                should be used. If false, a connection to Apple's Sandbox/Development
                APNs server will be established for this iOS variant.
              type: boolean
            pushApplicationId:
              description: PushApplicationId is the Id of the Application that this
                Variant corresponds to in the UnifiedPush Server admin UI.
              type: string
            teamId:
              description: TeamId is used if you are using APNs tokens as opposed
                to certificates.  Get this value from your APNS console.
              type: string
          required:
            - teamId
            - keyId
            - bundleId
            - privateKey
            - production
            - pushApplicationId
          type: object
        status:
          properties:
            ready:
              type: boolean
            secret:
              type: string
            variantId:
              type: string
          required:
            - ready
          type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
